name: Build (iOS)
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  
jobs:

  build_ios:
    name: Build Flutter (iOS)
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: "12.x"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.9.0-8.0.pre.9'
        channel: master
    - run: flutter pub get
    - run: flutter clean
    - run: flutter build ios --no-codesign
