name: Build (Android)
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  
jobs:

  build_android:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: "12.x"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.7'
        channel: stable
    - run: flutter pub get
    - run: flutter clean
    - run: flutter build appbundle
