name: Analyze and Test
on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  
jobs:
  flutter_analyze:
    name: Analyze flutter project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: "12.x"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.9.0-8.0.pre.9'
        channel: master
    - run: flutter pub get
    - run: flutter analyze
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: "12.x"
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.9.0-8.0.pre.9'
        channel: master
    - run: flutter test
